# Generated by Django 2.2.7 on 2019-11-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'get_latest_by': 'order_date'},
        ),
    ]
